#!/usr/bin/python3
import random
from enum import Enum


class Noun_Type(Enum):
    unspecified = 0
    animal = 1
    human = 2
    inanimate = 3


class Article_Type(Enum):
    improper = 0
    human = 2
    inanimate = 3


class Verb_Type(Enum):
    either = 0
    inanimate = 1
    animate = 2


class Prepositions(Enum):
    on_ = 0
    in_ = 1


# Word before the noun

nouns = [("cat", Noun_Type.animal), ("mat", Noun_Type.inanimate), ("banana", Noun_Type.inanimate),
         ("code dojo", Noun_Type.inanimate), ("Tom", Noun_Type.human), ("people", Noun_Type.inanimate),
         ("history", Noun_Type.inanimate),
         ("way", Noun_Type.inanimate),
         ("art", Noun_Type.inanimate),
         ("world", Noun_Type.inanimate),
         ("information", Noun_Type.inanimate),
         ("map", Noun_Type.inanimate),
         ("two", Noun_Type.inanimate),
         ("family", Noun_Type.inanimate),
         ("government", Noun_Type.inanimate),
         ("health", Noun_Type.inanimate),
         ("system", Noun_Type.inanimate),
         ("computer", Noun_Type.inanimate),
         ("meat", Noun_Type.inanimate),
         ("year", Noun_Type.inanimate),
         ("thanks", Noun_Type.inanimate),
         ("music", Noun_Type.inanimate),
         ("person", Noun_Type.inanimate),
         ("reading", Noun_Type.inanimate),
         ("method", Noun_Type.inanimate),
         ("data", Noun_Type.inanimate),
         ("food", Noun_Type.inanimate),
         ("understanding", Noun_Type.inanimate),
         ("theory", Noun_Type.inanimate),
         ("law", Noun_Type.inanimate),
         ("bird", Noun_Type.inanimate),
         ("literature", Noun_Type.inanimate),
         ("problem", Noun_Type.inanimate),
         ("software", Noun_Type.inanimate),
         ("control", Noun_Type.inanimate),
         ("knowledge", Noun_Type.inanimate),
         ("power", Noun_Type.inanimate),
         ("ability", Noun_Type.inanimate),
         ("economics", Noun_Type.inanimate),
         ("love", Noun_Type.inanimate),
         ("internet", Noun_Type.inanimate),
         ("television", Noun_Type.inanimate),
         ("science", Noun_Type.inanimate),
         ("library", Noun_Type.inanimate),
         ("nature", Noun_Type.inanimate),
         ("fact", Noun_Type.inanimate),
         ("product", Noun_Type.inanimate),
         ("idea", Noun_Type.inanimate),
         ("temperature", Noun_Type.inanimate),
         ("investment", Noun_Type.inanimate),
         ("area", Noun_Type.inanimate),
         ("society", Noun_Type.inanimate),
         ("activity", Noun_Type.inanimate),
         ("story", Noun_Type.inanimate),
         ("industry", Noun_Type.inanimate),
         ("media", Noun_Type.inanimate),
         ("thing", Noun_Type.inanimate),
         ("oven", Noun_Type.inanimate),
         ("community", Noun_Type.inanimate),
         ("definition", Noun_Type.inanimate),
         ("safety", Noun_Type.inanimate),
         ("quality", Noun_Type.inanimate),
         ("development", Noun_Type.inanimate),
         ("language", Noun_Type.inanimate),
         ("management", Noun_Type.inanimate),
         ("player", Noun_Type.inanimate),
         ("variety", Noun_Type.inanimate),
         ("video", Noun_Type.inanimate),
         ("week", Noun_Type.inanimate),
         ("security", Noun_Type.inanimate),
         ("country", Noun_Type.inanimate),
         ("exam", Noun_Type.inanimate),
         ("movie", Noun_Type.inanimate),
         ("organization", Noun_Type.inanimate),
         ("equipment", Noun_Type.inanimate),
         ("physics", Noun_Type.inanimate),
         ("analysis", Noun_Type.inanimate),
         ("policy", Noun_Type.inanimate),
         ("series", Noun_Type.inanimate),
         ("thought", Noun_Type.inanimate),
         ("basis", Noun_Type.inanimate),
         ("boyfriend", Noun_Type.inanimate),
         ("direction", Noun_Type.inanimate),
         ("strategy", Noun_Type.inanimate),
         ("technology", Noun_Type.inanimate),
         ("army", Noun_Type.inanimate),
         ("camera", Noun_Type.inanimate),
         ("freedom", Noun_Type.inanimate),
         ("paper", Noun_Type.inanimate),
         ("environment", Noun_Type.inanimate),
         ("child", Noun_Type.inanimate),
         ("instance", Noun_Type.inanimate),
         ("month", Noun_Type.inanimate),
         ("truth", Noun_Type.inanimate),
         ("marketing", Noun_Type.inanimate),
         ("university", Noun_Type.inanimate),
         ("writing", Noun_Type.inanimate),
         ("article", Noun_Type.inanimate),
         ("department", Noun_Type.inanimate),
         ("difference", Noun_Type.inanimate),
         ("goal", Noun_Type.inanimate),
         ("news", Noun_Type.inanimate),
         ("audience", Noun_Type.inanimate),
         ("fishing", Noun_Type.inanimate),
         ("growth", Noun_Type.inanimate),
         ("income", Noun_Type.inanimate),
         ("marriage", Noun_Type.inanimate),
         ("user", Noun_Type.inanimate),
         ("combination", Noun_Type.inanimate),
         ("failure", Noun_Type.inanimate),
         ("meaning", Noun_Type.inanimate),
         ("medicine", Noun_Type.inanimate),
         ("philosophy", Noun_Type.inanimate),
         ("teacher", Noun_Type.inanimate),
         ("communication", Noun_Type.inanimate),
         ("night", Noun_Type.inanimate),
         ("chemistry", Noun_Type.inanimate),
         ("disease", Noun_Type.inanimate),
         ("disk", Noun_Type.inanimate),
         ("energy", Noun_Type.inanimate),
         ("nation", Noun_Type.inanimate),
         ("road", Noun_Type.inanimate),
         ("role", Noun_Type.inanimate),
         ("soup", Noun_Type.inanimate),
         ("advertising", Noun_Type.inanimate),
         ("location", Noun_Type.inanimate),
         ("success", Noun_Type.inanimate),
         ("addition", Noun_Type.inanimate),
         ("apartment", Noun_Type.inanimate),
         ("education", Noun_Type.inanimate),
         ("math", Noun_Type.inanimate),
         ("moment", Noun_Type.inanimate),
         ("painting", Noun_Type.inanimate),
         ("politics", Noun_Type.inanimate),
         ("attention", Noun_Type.inanimate),
         ("decision", Noun_Type.inanimate),
         ("event", Noun_Type.inanimate),
         ("property", Noun_Type.inanimate),
         ("shopping", Noun_Type.inanimate),
         ("student", Noun_Type.inanimate),
         ("wood", Noun_Type.inanimate),
         ("competition", Noun_Type.inanimate),
         ("distribution", Noun_Type.inanimate),
         ("entertainment", Noun_Type.inanimate),
         ("office", Noun_Type.inanimate),
         ("population", Noun_Type.inanimate),
         ("president", Noun_Type.inanimate),
         ("unit", Noun_Type.inanimate),
         ("category", Noun_Type.inanimate),
         ("cigarette", Noun_Type.inanimate),
         ("context", Noun_Type.inanimate),
         ("introduction", Noun_Type.inanimate),
         ("opportunity", Noun_Type.inanimate),
         ("performance", Noun_Type.inanimate),
         ("driver", Noun_Type.inanimate),
         ("flight", Noun_Type.inanimate),
         ("length", Noun_Type.inanimate),
         ("magazine", Noun_Type.inanimate),
         ("newspaper", Noun_Type.inanimate),
         ("relationship", Noun_Type.inanimate),
         ("teaching", Noun_Type.inanimate),
         ("cell", Noun_Type.inanimate),
         ("dealer", Noun_Type.inanimate),
         ("finding", Noun_Type.inanimate),
         ("lake", Noun_Type.inanimate),
         ("member", Noun_Type.inanimate),
         ("message", Noun_Type.inanimate),
         ("phone", Noun_Type.inanimate),
         ("scene", Noun_Type.inanimate),
         ("appearance", Noun_Type.inanimate),
         ("association", Noun_Type.inanimate),
         ("concept", Noun_Type.inanimate),
         ("customer", Noun_Type.inanimate),
         ("death", Noun_Type.inanimate),
         ("discussion", Noun_Type.inanimate),
         ("housing", Noun_Type.inanimate),
         ("inflation", Noun_Type.inanimate),
         ("insurance", Noun_Type.inanimate),
         ("mood", Noun_Type.inanimate),
         ("woman", Noun_Type.inanimate),
         ("advice", Noun_Type.inanimate),
         ("blood", Noun_Type.inanimate),
         ("effort", Noun_Type.inanimate),
         ("expression", Noun_Type.inanimate),
         ("importance", Noun_Type.inanimate),
         ("opinion", Noun_Type.inanimate),
         ("payment", Noun_Type.inanimate),
         ("reality", Noun_Type.inanimate),
         ("responsibility", Noun_Type.inanimate),
         ("situation", Noun_Type.inanimate),
         ("skill", Noun_Type.inanimate),
         ("statement", Noun_Type.inanimate),
         ("wealth", Noun_Type.inanimate),
         ("application", Noun_Type.inanimate),
         ("city", Noun_Type.inanimate),
         ("county", Noun_Type.inanimate),
         ("depth", Noun_Type.inanimate),
         ("estate", Noun_Type.inanimate),
         ("foundation", Noun_Type.inanimate),
         ("grandmother", Noun_Type.inanimate),
         ("heart", Noun_Type.inanimate),
         ("perspective", Noun_Type.inanimate),
         ("photo", Noun_Type.inanimate),
         ("recipe", Noun_Type.inanimate),
         ("studio", Noun_Type.inanimate),
         ("topic", Noun_Type.inanimate),
         ("collection", Noun_Type.inanimate),
         ("depression", Noun_Type.inanimate),
         ("imagination", Noun_Type.inanimate),
         ("passion", Noun_Type.inanimate),
         ("percentage", Noun_Type.inanimate),
         ("resource", Noun_Type.inanimate),
         ("setting", Noun_Type.inanimate),
         ("ad", Noun_Type.inanimate),
         ("agency", Noun_Type.inanimate),
         ("college", Noun_Type.inanimate),
         ("connection", Noun_Type.inanimate),
         ("criticism", Noun_Type.inanimate),
         ("debt", Noun_Type.inanimate),
         ("description", Noun_Type.inanimate),
         ("memory", Noun_Type.inanimate),
         ("patience", Noun_Type.inanimate),
         ("secretary", Noun_Type.inanimate),
         ("solution", Noun_Type.inanimate),
         ("administration", Noun_Type.inanimate),
         ("aspect", Noun_Type.inanimate),
         ("attitude", Noun_Type.inanimate),
         ("director", Noun_Type.inanimate),
         ("personality", Noun_Type.inanimate),
         ("psychology", Noun_Type.inanimate),
         ("recommendation", Noun_Type.inanimate),
         ("response", Noun_Type.inanimate),
         ("selection", Noun_Type.inanimate),
         ("storage", Noun_Type.inanimate),
         ("version", Noun_Type.inanimate),
         ("alcohol", Noun_Type.inanimate),
         ("argument", Noun_Type.inanimate),
         ("complaint", Noun_Type.inanimate),
         ("contract", Noun_Type.inanimate),
         ("emphasis", Noun_Type.inanimate),
         ("highway", Noun_Type.inanimate),
         ("loss", Noun_Type.inanimate),
         ("membership", Noun_Type.inanimate),
         ("possession", Noun_Type.inanimate),
         ("preparation", Noun_Type.inanimate),
         ("steak", Noun_Type.inanimate),
         ("union", Noun_Type.inanimate),
         ("agreement", Noun_Type.inanimate),
         ("cancer", Noun_Type.inanimate),
         ("currency", Noun_Type.inanimate),
         ("employment", Noun_Type.inanimate),
         ("engineering", Noun_Type.inanimate),
         ("entry", Noun_Type.inanimate),
         ("interaction", Noun_Type.inanimate),
         ("mixture", Noun_Type.inanimate),
         ("preference", Noun_Type.inanimate),
         ("region", Noun_Type.inanimate),
         ("republic", Noun_Type.inanimate),
         ("tradition", Noun_Type.inanimate),
         ("virus", Noun_Type.inanimate),
         ("actor", Noun_Type.inanimate),
         ("classroom", Noun_Type.inanimate),
         ("delivery", Noun_Type.inanimate),
         ("device", Noun_Type.inanimate),
         ("difficulty", Noun_Type.inanimate),
         ("drama", Noun_Type.inanimate),
         ("election", Noun_Type.inanimate),
         ("engine", Noun_Type.inanimate),
         ("football", Noun_Type.inanimate),
         ("guidance", Noun_Type.inanimate),
         ("hotel", Noun_Type.inanimate),
         ("owner", Noun_Type.inanimate),
         ("priority", Noun_Type.inanimate),
         ("protection", Noun_Type.inanimate),
         ("suggestion", Noun_Type.inanimate),
         ("tension", Noun_Type.inanimate),
         ("variation", Noun_Type.inanimate),
         ("anxiety", Noun_Type.inanimate),
         ("atmosphere", Noun_Type.inanimate),
         ("awareness", Noun_Type.inanimate),
         ("bath", Noun_Type.inanimate),
         ("bread", Noun_Type.inanimate),
         ("candidate", Noun_Type.inanimate),
         ("climate", Noun_Type.inanimate),
         ("comparison", Noun_Type.inanimate),
         ("confusion", Noun_Type.inanimate),
         ("construction", Noun_Type.inanimate),
         ("elevator", Noun_Type.inanimate),
         ("emotion", Noun_Type.inanimate),
         ("employee", Noun_Type.inanimate),
         ("employer", Noun_Type.inanimate),
         ("guest", Noun_Type.inanimate),
         ("height", Noun_Type.inanimate),
         ("leadership", Noun_Type.inanimate),
         ("mall", Noun_Type.inanimate),
         ("manager", Noun_Type.inanimate),
         ("operation", Noun_Type.inanimate),
         ("recording", Noun_Type.inanimate),
         ("sample", Noun_Type.inanimate),
         ("transportation", Noun_Type.inanimate),
         ("charity", Noun_Type.inanimate),
         ("cousin", Noun_Type.inanimate),
         ("disaster", Noun_Type.inanimate),
         ("editor", Noun_Type.inanimate),
         ("efficiency", Noun_Type.inanimate),
         ("excitement", Noun_Type.inanimate),
         ("extent", Noun_Type.inanimate),
         ("feedback", Noun_Type.inanimate),
         ("guitar", Noun_Type.inanimate),
         ("homework", Noun_Type.inanimate),
         ("leader", Noun_Type.inanimate),
         ("mom", Noun_Type.inanimate),
         ("outcome", Noun_Type.inanimate),
         ("permission", Noun_Type.inanimate),
         ("presentation", Noun_Type.inanimate),
         ("promotion", Noun_Type.inanimate),
         ("reflection", Noun_Type.inanimate),
         ("refrigerator", Noun_Type.inanimate),
         ("resolution", Noun_Type.inanimate),
         ("revenue", Noun_Type.inanimate),
         ("session", Noun_Type.inanimate),
         ("singer", Noun_Type.inanimate),
         ("tennis", Noun_Type.inanimate),
         ("basket", Noun_Type.inanimate),
         ("bonus", Noun_Type.inanimate),
         ("cabinet", Noun_Type.inanimate),
         ("childhood", Noun_Type.inanimate),
         ("church", Noun_Type.inanimate),
         ("clothes", Noun_Type.inanimate),
         ("coffee", Noun_Type.inanimate),
         ("dinner", Noun_Type.inanimate),
         ("drawing", Noun_Type.inanimate),
         ("hair", Noun_Type.inanimate),
         ("hearing", Noun_Type.inanimate),
         ("initiative", Noun_Type.inanimate),
         ("judgment", Noun_Type.inanimate),
         ("lab", Noun_Type.inanimate),
         ("measurement", Noun_Type.inanimate),
         ("mode", Noun_Type.inanimate),
         ("mud", Noun_Type.inanimate),
         ("orange", Noun_Type.inanimate),
         ("poetry", Noun_Type.inanimate),
         ("police", Noun_Type.inanimate),
         ("possibility", Noun_Type.inanimate),
         ("procedure", Noun_Type.inanimate),
         ("queen", Noun_Type.inanimate),
         ("ratio", Noun_Type.inanimate),
         ("relation", Noun_Type.inanimate),
         ("restaurant", Noun_Type.inanimate),
         ("satisfaction", Noun_Type.inanimate),
         ("sector", Noun_Type.inanimate),
         ("signature", Noun_Type.inanimate),
         ("significance", Noun_Type.inanimate),
         ("song", Noun_Type.inanimate),
         ("tooth", Noun_Type.inanimate),
         ("town", Noun_Type.inanimate),
         ("vehicle", Noun_Type.inanimate),
         ("volume", Noun_Type.inanimate),
         ("wife", Noun_Type.inanimate),
         ("accident", Noun_Type.inanimate),
         ("airport", Noun_Type.inanimate),
         ("appointment", Noun_Type.inanimate),
         ("arrival", Noun_Type.inanimate),
         ("assumption", Noun_Type.inanimate),
         ("baseball", Noun_Type.inanimate),
         ("chapter", Noun_Type.inanimate),
         ("committee", Noun_Type.inanimate),
         ("conversation", Noun_Type.inanimate),
         ("database", Noun_Type.inanimate),
         ("enthusiasm", Noun_Type.inanimate),
         ("error", Noun_Type.inanimate),
         ("explanation", Noun_Type.inanimate),
         ("farmer", Noun_Type.inanimate),
         ("gate", Noun_Type.inanimate),
         ("girl", Noun_Type.inanimate),
         ("hall", Noun_Type.inanimate),
         ("historian", Noun_Type.inanimate),
         ("hospital", Noun_Type.inanimate),
         ("injury", Noun_Type.inanimate),
         ("instruction", Noun_Type.inanimate),
         ("maintenance", Noun_Type.inanimate),
         ("manufacturer", Noun_Type.inanimate),
         ("meal", Noun_Type.inanimate),
         ("perception", Noun_Type.inanimate),
         ("pie", Noun_Type.inanimate),
         ("poem", Noun_Type.inanimate),
         ("presence", Noun_Type.inanimate),
         ("proposal", Noun_Type.inanimate),
         ("reception", Noun_Type.inanimate),
         ("replacement", Noun_Type.inanimate),
         ("revolution", Noun_Type.inanimate),
         ("river", Noun_Type.inanimate),
         ("son", Noun_Type.inanimate),
         ("speech", Noun_Type.inanimate),
         ("tea", Noun_Type.inanimate),
         ("village", Noun_Type.inanimate),
         ("warning", Noun_Type.inanimate),
         ("winner", Noun_Type.inanimate),
         ("worker", Noun_Type.inanimate),
         ("writer", Noun_Type.inanimate),
         ("assistance", Noun_Type.inanimate),
         ("breath", Noun_Type.inanimate),
         ("buyer", Noun_Type.inanimate),
         ("chest", Noun_Type.inanimate),
         ("chocolate", Noun_Type.inanimate),
         ("conclusion", Noun_Type.inanimate),
         ("contribution", Noun_Type.inanimate),
         ("cookie", Noun_Type.inanimate),
         ("courage", Noun_Type.inanimate),
         ("dad", Noun_Type.inanimate),
         ("desk", Noun_Type.inanimate),
         ("drawer", Noun_Type.inanimate),
         ("establishment", Noun_Type.inanimate),
         ("examination", Noun_Type.inanimate),
         ("garbage", Noun_Type.inanimate),
         ("grocery", Noun_Type.inanimate),
         ("honey", Noun_Type.inanimate),
         ("impression", Noun_Type.inanimate),
         ("improvement", Noun_Type.inanimate),
         ("independence", Noun_Type.inanimate),
         ("insect", Noun_Type.inanimate),
         ("inspection", Noun_Type.inanimate),
         ("inspector", Noun_Type.inanimate),
         ("king", Noun_Type.inanimate),
         ("ladder", Noun_Type.inanimate),
         ("menu", Noun_Type.inanimate),
         ("penalty", Noun_Type.inanimate),
         ("piano", Noun_Type.inanimate),
         ("potato", Noun_Type.inanimate),
         ("profession", Noun_Type.inanimate),
         ("professor", Noun_Type.inanimate),
         ("quantity", Noun_Type.inanimate),
         ("reaction", Noun_Type.inanimate),
         ("requirement", Noun_Type.inanimate),
         ("salad", Noun_Type.inanimate),
         ("sister", Noun_Type.inanimate),
         ("supermarket", Noun_Type.inanimate),
         ("tongue", Noun_Type.inanimate),
         ("weakness", Noun_Type.inanimate),
         ("wedding", Noun_Type.inanimate),
         ("affair", Noun_Type.inanimate),
         ("ambition", Noun_Type.inanimate),
         ("analyst", Noun_Type.inanimate),
         ("apple", Noun_Type.inanimate),
         ("assignment", Noun_Type.inanimate),
         ("assistant", Noun_Type.inanimate),
         ("bathroom", Noun_Type.inanimate),
         ("bedroom", Noun_Type.inanimate),
         ("beer", Noun_Type.inanimate),
         ("birthday", Noun_Type.inanimate),
         ("celebration", Noun_Type.inanimate),
         ("championship", Noun_Type.inanimate),
         ("cheek", Noun_Type.inanimate),
         ("client", Noun_Type.inanimate),
         ("consequence", Noun_Type.inanimate),
         ("departure", Noun_Type.inanimate),
         ("diamond", Noun_Type.inanimate),
         ("dirt", Noun_Type.inanimate),
         ("ear", Noun_Type.inanimate),
         ("fortune", Noun_Type.inanimate),
         ("friendship", Noun_Type.inanimate),
         ("funeral", Noun_Type.inanimate),
         ("gene", Noun_Type.inanimate),
         ("girlfriend", Noun_Type.inanimate),
         ("hat", Noun_Type.inanimate),
         ("indication", Noun_Type.inanimate),
         ("intention", Noun_Type.inanimate),
         ("lady", Noun_Type.inanimate),
         ("midnight", Noun_Type.inanimate),
         ("negotiation", Noun_Type.inanimate),
         ("obligation", Noun_Type.inanimate),
         ("passenger", Noun_Type.inanimate),
         ("pizza", Noun_Type.inanimate),
         ("platform", Noun_Type.inanimate),
         ("poet", Noun_Type.inanimate),
         ("pollution", Noun_Type.inanimate),
         ("recognition", Noun_Type.inanimate),
         ("reputation", Noun_Type.inanimate),
         ("shirt", Noun_Type.inanimate),
         ("sir", Noun_Type.inanimate),
         ("speaker", Noun_Type.inanimate),
         ("stranger", Noun_Type.inanimate),
         ("surgery", Noun_Type.inanimate),
         ("sympathy", Noun_Type.inanimate),
         ("tale", Noun_Type.inanimate),
         ("throat", Noun_Type.inanimate),
         ("trainer", Noun_Type.inanimate),
         ("uncle", Noun_Type.inanimate),
         ("youth", Noun_Type.inanimate),
         ("time", Noun_Type.inanimate),
         ("work", Noun_Type.inanimate),
         ("film", Noun_Type.inanimate),
         ("water", Noun_Type.inanimate),
         ("money", Noun_Type.inanimate),
         ("example", Noun_Type.inanimate),
         ("while", Noun_Type.inanimate),
         ("business", Noun_Type.inanimate),
         ("study", Noun_Type.inanimate),
         ("game", Noun_Type.inanimate),
         ("life", Noun_Type.inanimate),
         ("form", Noun_Type.inanimate),
         ("air", Noun_Type.inanimate),
         ("day", Noun_Type.inanimate),
         ("place", Noun_Type.inanimate),
         ("number", Noun_Type.inanimate),
         ("part", Noun_Type.inanimate),
         ("field", Noun_Type.inanimate),
         ("fish", Noun_Type.inanimate),
         ("back", Noun_Type.inanimate),
         ("process", Noun_Type.inanimate),
         ("heat", Noun_Type.inanimate),
         ("hand", Noun_Type.inanimate),
         ("experience", Noun_Type.inanimate),
         ("job", Noun_Type.inanimate),
         ("book", Noun_Type.inanimate),
         ("end", Noun_Type.inanimate),
         ("point", Noun_Type.inanimate),
         ("type", Noun_Type.inanimate),
         ("home", Noun_Type.inanimate),
         ("economy", Noun_Type.inanimate),
         ("value", Noun_Type.inanimate),
         ("body", Noun_Type.inanimate),
         ("market", Noun_Type.inanimate),
         ("guide", Noun_Type.inanimate),
         ("interest", Noun_Type.inanimate),
         ("state", Noun_Type.inanimate),
         ("radio", Noun_Type.inanimate),
         ("course", Noun_Type.inanimate),
         ("company", Noun_Type.inanimate),
         ("price", Noun_Type.inanimate),
         ("size", Noun_Type.inanimate),
         ("card", Noun_Type.inanimate),
         ("list", Noun_Type.inanimate),
         ("mind", Noun_Type.inanimate),
         ("trade", Noun_Type.inanimate),
         ("line", Noun_Type.inanimate),
         ("care", Noun_Type.inanimate),
         ("group", Noun_Type.inanimate),
         ("risk", Noun_Type.inanimate),
         ("word", Noun_Type.inanimate),
         ("fat", Noun_Type.inanimate),
         ("force", Noun_Type.inanimate),
         ("key", Noun_Type.inanimate),
         ("light", Noun_Type.inanimate),
         ("training", Noun_Type.inanimate),
         ("name", Noun_Type.inanimate),
         ("school", Noun_Type.inanimate),
         ("top", Noun_Type.inanimate),
         ("amount", Noun_Type.inanimate),
         ("level", Noun_Type.inanimate),
         ("order", Noun_Type.inanimate),
         ("practice", Noun_Type.inanimate),
         ("research", Noun_Type.inanimate),
         ("sense", Noun_Type.inanimate),
         ("service", Noun_Type.inanimate),
         ("piece", Noun_Type.inanimate),
         ("web", Noun_Type.inanimate),
         ("boss", Noun_Type.inanimate),
         ("sport", Noun_Type.inanimate),
         ("fun", Noun_Type.inanimate),
         ("house", Noun_Type.inanimate),
         ("page", Noun_Type.inanimate),
         ("term", Noun_Type.inanimate),
         ("test", Noun_Type.inanimate),
         ("answer", Noun_Type.inanimate),
         ("sound", Noun_Type.inanimate),
         ("focus", Noun_Type.inanimate),
         ("matter", Noun_Type.inanimate),
         ("kind", Noun_Type.inanimate),
         ("soil", Noun_Type.inanimate),
         ("board", Noun_Type.inanimate),
         ("oil", Noun_Type.inanimate),
         ("picture", Noun_Type.inanimate),
         ("access", Noun_Type.inanimate),
         ("garden", Noun_Type.inanimate),
         ("range", Noun_Type.inanimate),
         ("rate", Noun_Type.inanimate),
         ("reason", Noun_Type.inanimate),
         ("future", Noun_Type.inanimate),
         ("site", Noun_Type.inanimate),
         ("demand", Noun_Type.inanimate),
         ("exercise", Noun_Type.inanimate),
         ("image", Noun_Type.inanimate),
         ("case", Noun_Type.inanimate),
         ("cause", Noun_Type.inanimate),
         ("coast", Noun_Type.inanimate),
         ("action", Noun_Type.inanimate),
         ("age", Noun_Type.inanimate),
         ("bad", Noun_Type.inanimate),
         ("boat", Noun_Type.inanimate),
         ("record", Noun_Type.inanimate),
         ("result", Noun_Type.inanimate),
         ("section", Noun_Type.inanimate),
         ("building", Noun_Type.inanimate),
         ("mouse", Noun_Type.inanimate),
         ("cash", Noun_Type.inanimate),
         ("class", Noun_Type.inanimate),
         ("nothing", Noun_Type.inanimate),
         ("period", Noun_Type.inanimate),
         ("plan", Noun_Type.inanimate),
         ("store", Noun_Type.inanimate),
         ("tax", Noun_Type.inanimate),
         ("side", Noun_Type.inanimate),
         ("subject", Noun_Type.inanimate),
         ("space", Noun_Type.inanimate),
         ("rule", Noun_Type.inanimate),
         ("stock", Noun_Type.inanimate),
         ("weather", Noun_Type.inanimate),
         ("chance", Noun_Type.inanimate),
         ("figure", Noun_Type.inanimate),
         ("man", Noun_Type.inanimate),
         ("model", Noun_Type.inanimate),
         ("source", Noun_Type.inanimate),
         ("beginning", Noun_Type.inanimate),
         ("earth", Noun_Type.inanimate),
         ("program", Noun_Type.inanimate),
         ("chicken", Noun_Type.inanimate),
         ("design", Noun_Type.inanimate),
         ("feature", Noun_Type.inanimate),
         ("head", Noun_Type.inanimate),
         ("material", Noun_Type.inanimate),
         ("purpose", Noun_Type.inanimate),
         ("question", Noun_Type.inanimate),
         ("rock", Noun_Type.inanimate),
         ("salt", Noun_Type.inanimate),
         ("act", Noun_Type.inanimate),
         ("birth", Noun_Type.inanimate),
         ("car", Noun_Type.inanimate),
         ("dog", Noun_Type.inanimate),
         ("object", Noun_Type.inanimate),
         ("scale", Noun_Type.inanimate),
         ("sun", Noun_Type.inanimate),
         ("note", Noun_Type.inanimate),
         ("profit", Noun_Type.inanimate),
         ("rent", Noun_Type.inanimate),
         ("speed", Noun_Type.inanimate),
         ("style", Noun_Type.inanimate),
         ("war", Noun_Type.inanimate),
         ("bank", Noun_Type.inanimate),
         ("craft", Noun_Type.inanimate),
         ("half", Noun_Type.inanimate),
         ("inside", Noun_Type.inanimate),
         ("outside", Noun_Type.inanimate),
         ("standard", Noun_Type.inanimate),
         ("bus", Noun_Type.inanimate),
         ("exchange", Noun_Type.inanimate),
         ("eye", Noun_Type.inanimate),
         ("fire", Noun_Type.inanimate),
         ("position", Noun_Type.inanimate),
         ("pressure", Noun_Type.inanimate),
         ("stress", Noun_Type.inanimate),
         ("advantage", Noun_Type.inanimate),
         ("benefit", Noun_Type.inanimate),
         ("box", Noun_Type.inanimate),
         ("frame", Noun_Type.inanimate),
         ("issue", Noun_Type.inanimate),
         ("step", Noun_Type.inanimate),
         ("cycle", Noun_Type.inanimate),
         ("face", Noun_Type.inanimate),
         ("item", Noun_Type.inanimate),
         ("metal", Noun_Type.inanimate),
         ("paint", Noun_Type.inanimate),
         ("review", Noun_Type.inanimate),
         ("room", Noun_Type.inanimate),
         ("screen", Noun_Type.inanimate),
         ("structure", Noun_Type.inanimate),
         ("view", Noun_Type.inanimate),
         ("account", Noun_Type.inanimate),
         ("ball", Noun_Type.inanimate),
         ("discipline", Noun_Type.inanimate),
         ("medium", Noun_Type.inanimate),
         ("share", Noun_Type.inanimate),
         ("balance", Noun_Type.inanimate),
         ("bit", Noun_Type.inanimate),
         ("black", Noun_Type.inanimate),
         ("bottom", Noun_Type.inanimate),
         ("choice", Noun_Type.inanimate),
         ("gift", Noun_Type.inanimate),
         ("impact", Noun_Type.inanimate),
         ("machine", Noun_Type.inanimate),
         ("shape", Noun_Type.inanimate),
         ("tool", Noun_Type.inanimate),
         ("wind", Noun_Type.inanimate),
         ("address", Noun_Type.inanimate),
         ("average", Noun_Type.inanimate),
         ("career", Noun_Type.inanimate),
         ("culture", Noun_Type.inanimate),
         ("morning", Noun_Type.inanimate),
         ("pot", Noun_Type.inanimate),
         ("sign", Noun_Type.inanimate),
         ("table", Noun_Type.inanimate),
         ("task", Noun_Type.inanimate),
         ("condition", Noun_Type.inanimate),
         ("contact", Noun_Type.inanimate),
         ("credit", Noun_Type.inanimate),
         ("egg", Noun_Type.inanimate),
         ("hope", Noun_Type.inanimate),
         ("ice", Noun_Type.inanimate),
         ("network", Noun_Type.inanimate),
         ("north", Noun_Type.inanimate),
         ("square", Noun_Type.inanimate),
         ("attempt", Noun_Type.inanimate),
         ("date", Noun_Type.inanimate),
         ("effect", Noun_Type.inanimate),
         ("link", Noun_Type.inanimate),
         ("post", Noun_Type.inanimate),
         ("star", Noun_Type.inanimate),
         ("voice", Noun_Type.inanimate),
         ("capital", Noun_Type.inanimate),
         ("challenge", Noun_Type.inanimate),
         ("friend", Noun_Type.inanimate),
         ("self", Noun_Type.inanimate),
         ("shot", Noun_Type.inanimate),
         ("brush", Noun_Type.inanimate),
         ("couple", Noun_Type.inanimate),
         ("debate", Noun_Type.inanimate),
         ("exit", Noun_Type.inanimate),
         ("front", Noun_Type.inanimate),
         ("function", Noun_Type.inanimate),
         ("lack", Noun_Type.inanimate),
         ("living", Noun_Type.inanimate),
         ("plant", Noun_Type.inanimate),
         ("plastic", Noun_Type.inanimate),
         ("spot", Noun_Type.inanimate),
         ("summer", Noun_Type.inanimate),
         ("taste", Noun_Type.inanimate),
         ("theme", Noun_Type.inanimate),
         ("track", Noun_Type.inanimate),
         ("wing", Noun_Type.inanimate),
         ("brain", Noun_Type.inanimate),
         ("button", Noun_Type.inanimate),
         ("click", Noun_Type.inanimate),
         ("desire", Noun_Type.inanimate),
         ("foot", Noun_Type.inanimate),
         ("gas", Noun_Type.inanimate),
         ("influence", Noun_Type.inanimate),
         ("notice", Noun_Type.inanimate),
         ("rain", Noun_Type.inanimate),
         ("wall", Noun_Type.inanimate),
         ("base", Noun_Type.inanimate),
         ("damage", Noun_Type.inanimate),
         ("distance", Noun_Type.inanimate),
         ("feeling", Noun_Type.inanimate),
         ("pair", Noun_Type.inanimate),
         ("savings", Noun_Type.inanimate),
         ("staff", Noun_Type.inanimate),
         ("sugar", Noun_Type.inanimate),
         ("target", Noun_Type.inanimate),
         ("text", Noun_Type.inanimate),
         ("animal", Noun_Type.inanimate),
         ("author", Noun_Type.inanimate),
         ("budget", Noun_Type.inanimate),
         ("discount", Noun_Type.inanimate),
         ("file", Noun_Type.inanimate),
         ("ground", Noun_Type.inanimate),
         ("lesson", Noun_Type.inanimate),
         ("minute", Noun_Type.inanimate),
         ("officer", Noun_Type.inanimate),
         ("phase", Noun_Type.inanimate),
         ("reference", Noun_Type.inanimate),
         ("register", Noun_Type.inanimate),
         ("sky", Noun_Type.inanimate),
         ("stage", Noun_Type.inanimate),
         ("stick", Noun_Type.inanimate),
         ("title", Noun_Type.inanimate),
         ("trouble", Noun_Type.inanimate),
         ("bowl", Noun_Type.inanimate),
         ("bridge", Noun_Type.inanimate),
         ("campaign", Noun_Type.inanimate),
         ("character", Noun_Type.inanimate),
         ("club", Noun_Type.inanimate),
         ("edge", Noun_Type.inanimate),
         ("evidence", Noun_Type.inanimate),
         ("fan", Noun_Type.inanimate),
         ("letter", Noun_Type.inanimate),
         ("lock", Noun_Type.inanimate),
         ("maximum", Noun_Type.inanimate),
         ("novel", Noun_Type.inanimate),
         ("option", Noun_Type.inanimate),
         ("pack", Noun_Type.inanimate),
         ("park", Noun_Type.inanimate),
         ("plenty", Noun_Type.inanimate),
         ("quarter", Noun_Type.inanimate),
         ("skin", Noun_Type.inanimate),
         ("sort", Noun_Type.inanimate),
         ("weight", Noun_Type.inanimate),
         ("baby", Noun_Type.inanimate),
         ("background", Noun_Type.inanimate),
         ("carry", Noun_Type.inanimate),
         ("dish", Noun_Type.inanimate),
         ("factor", Noun_Type.inanimate),
         ("fruit", Noun_Type.inanimate),
         ("glass", Noun_Type.inanimate),
         ("joint", Noun_Type.inanimate),
         ("master", Noun_Type.inanimate),
         ("muscle", Noun_Type.inanimate),
         ("red", Noun_Type.inanimate),
         ("strength", Noun_Type.inanimate),
         ("traffic", Noun_Type.inanimate),
         ("trip", Noun_Type.inanimate),
         ("vegetable", Noun_Type.inanimate),
         ("appeal", Noun_Type.inanimate),
         ("chart", Noun_Type.inanimate),
         ("gear", Noun_Type.inanimate),
         ("ideal", Noun_Type.inanimate),
         ("kitchen", Noun_Type.inanimate),
         ("land", Noun_Type.inanimate),
         ("log", Noun_Type.inanimate),
         ("mother", Noun_Type.inanimate),
         ("net", Noun_Type.inanimate),
         ("party", Noun_Type.inanimate),
         ("principle", Noun_Type.inanimate),
         ("relative", Noun_Type.inanimate),
         ("sale", Noun_Type.inanimate),
         ("season", Noun_Type.inanimate),
         ("signal", Noun_Type.inanimate),
         ("spirit", Noun_Type.inanimate),
         ("street", Noun_Type.inanimate),
         ("tree", Noun_Type.inanimate),
         ("wave", Noun_Type.inanimate),
         ("belt", Noun_Type.inanimate),
         ("bench", Noun_Type.inanimate),
         ("commission", Noun_Type.inanimate),
         ("copy", Noun_Type.inanimate),
         ("drop", Noun_Type.inanimate),
         ("minimum", Noun_Type.inanimate),
         ("path", Noun_Type.inanimate),
         ("progress", Noun_Type.inanimate),
         ("project", Noun_Type.inanimate),
         ("sea", Noun_Type.inanimate),
         ("south", Noun_Type.inanimate),
         ("status", Noun_Type.inanimate),
         ("stuff", Noun_Type.inanimate),
         ("ticket", Noun_Type.inanimate),
         ("tour", Noun_Type.inanimate),
         ("angle", Noun_Type.inanimate),
         ("blue", Noun_Type.inanimate),
         ("breakfast", Noun_Type.inanimate),
         ("confidence", Noun_Type.inanimate),
         ("daughter", Noun_Type.inanimate),
         ("degree", Noun_Type.inanimate),
         ("doctor", Noun_Type.inanimate),
         ("dot", Noun_Type.inanimate),
         ("dream", Noun_Type.inanimate),
         ("duty", Noun_Type.inanimate),
         ("essay", Noun_Type.inanimate),
         ("father", Noun_Type.inanimate),
         ("fee", Noun_Type.inanimate),
         ("finance", Noun_Type.inanimate),
         ("hour", Noun_Type.inanimate),
         ("juice", Noun_Type.inanimate),
         ("limit", Noun_Type.inanimate),
         ("luck", Noun_Type.inanimate),
         ("milk", Noun_Type.inanimate),
         ("mouth", Noun_Type.inanimate),
         ("peace", Noun_Type.inanimate),
         ("pipe", Noun_Type.inanimate),
         ("seat", Noun_Type.inanimate),
         ("stable", Noun_Type.inanimate),
         ("storm", Noun_Type.inanimate),
         ("substance", Noun_Type.inanimate),
         ("team", Noun_Type.inanimate),
         ("trick", Noun_Type.inanimate),
         ("afternoon", Noun_Type.inanimate),
         ("bat", Noun_Type.inanimate),
         ("beach", Noun_Type.inanimate),
         ("blank", Noun_Type.inanimate),
         ("catch", Noun_Type.inanimate),
         ("chain", Noun_Type.inanimate),
         ("consideration", Noun_Type.inanimate),
         ("cream", Noun_Type.inanimate),
         ("crew", Noun_Type.inanimate),
         ("detail", Noun_Type.inanimate),
         ("gold", Noun_Type.inanimate),
         ("interview", Noun_Type.inanimate),
         ("kid", Noun_Type.inanimate),
         ("mark", Noun_Type.inanimate),
         ("match", Noun_Type.inanimate),
         ("mission", Noun_Type.inanimate),
         ("pain", Noun_Type.inanimate),
         ("pleasure", Noun_Type.inanimate),
         ("score", Noun_Type.inanimate),
         ("screw", Noun_Type.inanimate),
         ("sex", Noun_Type.inanimate),
         ("shop", Noun_Type.inanimate),
         ("shower", Noun_Type.inanimate),
         ("suit", Noun_Type.inanimate),
         ("tone", Noun_Type.inanimate),
         ("window", Noun_Type.inanimate),
         ("agent", Noun_Type.inanimate),
         ("band", Noun_Type.inanimate),
         ("block", Noun_Type.inanimate),
         ("bone", Noun_Type.inanimate),
         ("calendar", Noun_Type.inanimate),
         ("cap", Noun_Type.inanimate),
         ("coat", Noun_Type.inanimate),
         ("contest", Noun_Type.inanimate),
         ("corner", Noun_Type.inanimate),
         ("court", Noun_Type.inanimate),
         ("cup", Noun_Type.inanimate),
         ("district", Noun_Type.inanimate),
         ("door", Noun_Type.inanimate),
         ("east", Noun_Type.inanimate),
         ("finger", Noun_Type.inanimate),
         ("garage", Noun_Type.inanimate),
         ("guarantee", Noun_Type.inanimate),
         ("hole", Noun_Type.inanimate),
         ("hook", Noun_Type.inanimate),
         ("implement", Noun_Type.inanimate),
         ("layer", Noun_Type.inanimate),
         ("lecture", Noun_Type.inanimate),
         ("lie", Noun_Type.inanimate),
         ("manner", Noun_Type.inanimate),
         ("meeting", Noun_Type.inanimate),
         ("nose", Noun_Type.inanimate),
         ("parking", Noun_Type.inanimate),
         ("partner", Noun_Type.inanimate),
         ("profile", Noun_Type.inanimate),
         ("respect", Noun_Type.inanimate),
         ("rice", Noun_Type.inanimate),
         ("routine", Noun_Type.inanimate),
         ("schedule", Noun_Type.inanimate),
         ("swimming", Noun_Type.inanimate),
         ("telephone", Noun_Type.inanimate),
         ("tip", Noun_Type.inanimate),
         ("winter", Noun_Type.inanimate),
         ("airline", Noun_Type.inanimate),
         ("bag", Noun_Type.inanimate),
         ("battle", Noun_Type.inanimate),
         ("bed", Noun_Type.inanimate),
         ("bill", Noun_Type.inanimate),
         ("bother", Noun_Type.inanimate),
         ("cake", Noun_Type.inanimate),
         ("code", Noun_Type.inanimate),
         ("curve", Noun_Type.inanimate),
         ("designer", Noun_Type.inanimate),
         ("dimension", Noun_Type.inanimate),
         ("dress", Noun_Type.inanimate),
         ("ease", Noun_Type.inanimate),
         ("emergency", Noun_Type.inanimate),
         ("evening", Noun_Type.inanimate),
         ("extension", Noun_Type.inanimate),
         ("farm", Noun_Type.inanimate),
         ("fight", Noun_Type.inanimate),
         ("gap", Noun_Type.inanimate),
         ("grade", Noun_Type.inanimate),
         ("holiday", Noun_Type.inanimate),
         ("horror", Noun_Type.inanimate),
         ("horse", Noun_Type.inanimate),
         ("host", Noun_Type.inanimate),
         ("husband", Noun_Type.inanimate),
         ("loan", Noun_Type.inanimate),
         ("mistake", Noun_Type.inanimate),
         ("mountain", Noun_Type.inanimate),
         ("nail", Noun_Type.inanimate),
         ("noise", Noun_Type.inanimate),
         ("occasion", Noun_Type.inanimate),
         ("package", Noun_Type.inanimate),
         ("patient", Noun_Type.inanimate),
         ("pause", Noun_Type.inanimate),
         ("phrase", Noun_Type.inanimate),
         ("proof", Noun_Type.inanimate),
         ("race", Noun_Type.inanimate),
         ("relief", Noun_Type.inanimate),
         ("sand", Noun_Type.inanimate),
         ("sentence", Noun_Type.inanimate),
         ("shoulder", Noun_Type.inanimate),
         ("smoke", Noun_Type.inanimate),
         ("stomach", Noun_Type.inanimate),
         ("string", Noun_Type.inanimate),
         ("tourist", Noun_Type.inanimate),
         ("towel", Noun_Type.inanimate),
         ("vacation", Noun_Type.inanimate),
         ("west", Noun_Type.inanimate),
         ("wheel", Noun_Type.inanimate),
         ("wine", Noun_Type.inanimate),
         ("arm", Noun_Type.inanimate),
         ("aside", Noun_Type.inanimate),
         ("associate", Noun_Type.inanimate),
         ("bet", Noun_Type.inanimate),
         ("blow", Noun_Type.inanimate),
         ("border", Noun_Type.inanimate),
         ("branch", Noun_Type.inanimate),
         ("breast", Noun_Type.inanimate),
         ("brother", Noun_Type.inanimate),
         ("buddy", Noun_Type.inanimate),
         ("bunch", Noun_Type.inanimate),
         ("chip", Noun_Type.inanimate),
         ("coach", Noun_Type.inanimate),
         ("cross", Noun_Type.inanimate),
         ("document", Noun_Type.inanimate),
         ("draft", Noun_Type.inanimate),
         ("dust", Noun_Type.inanimate),
         ("expert", Noun_Type.inanimate),
         ("floor", Noun_Type.inanimate),
         ("god", Noun_Type.inanimate),
         ("golf", Noun_Type.inanimate),
         ("habit", Noun_Type.inanimate),
         ("iron", Noun_Type.inanimate),
         ("judge", Noun_Type.inanimate),
         ("knife", Noun_Type.inanimate),
         ("landscape", Noun_Type.inanimate),
         ("league", Noun_Type.inanimate),
         ("mail", Noun_Type.inanimate),
         ("mess", Noun_Type.inanimate),
         ("native", Noun_Type.inanimate),
         ("opening", Noun_Type.inanimate),
         ("parent", Noun_Type.inanimate),
         ("pattern", Noun_Type.inanimate),
         ("pin", Noun_Type.inanimate),
         ("pool", Noun_Type.inanimate),
         ("pound", Noun_Type.inanimate),
         ("request", Noun_Type.inanimate),
         ("salary", Noun_Type.inanimate),
         ("shame", Noun_Type.inanimate),
         ("shelter", Noun_Type.inanimate),
         ("shoe", Noun_Type.inanimate),
         ("silver", Noun_Type.inanimate),
         ("tackle", Noun_Type.inanimate),
         ("tank", Noun_Type.inanimate),
         ("trust", Noun_Type.inanimate),
         ("assist", Noun_Type.inanimate),
         ("bake", Noun_Type.inanimate),
         ("bar", Noun_Type.inanimate),
         ("bell", Noun_Type.inanimate),
         ("bike", Noun_Type.inanimate),
         ("blame", Noun_Type.inanimate),
         ("boy", Noun_Type.inanimate),
         ("brick", Noun_Type.inanimate),
         ("chair", Noun_Type.inanimate),
         ("closet", Noun_Type.inanimate),
         ("clue", Noun_Type.inanimate),
         ("collar", Noun_Type.inanimate),
         ("comment", Noun_Type.inanimate),
         ("conference", Noun_Type.inanimate),
         ("devil", Noun_Type.inanimate),
         ("diet", Noun_Type.inanimate),
         ("fear", Noun_Type.inanimate),
         ("fuel", Noun_Type.inanimate),
         ("glove", Noun_Type.inanimate),
         ("jacket", Noun_Type.inanimate),
         ("lunch", Noun_Type.inanimate),
         ("monitor", Noun_Type.inanimate),
         ("mortgage", Noun_Type.inanimate),
         ("nurse", Noun_Type.inanimate),
         ("pace", Noun_Type.inanimate),
         ("panic", Noun_Type.inanimate),
         ("peak", Noun_Type.inanimate),
         ("plane", Noun_Type.inanimate),
         ("reward", Noun_Type.inanimate),
         ("row", Noun_Type.inanimate),
         ("sandwich", Noun_Type.inanimate),
         ("shock", Noun_Type.inanimate),
         ("spite", Noun_Type.inanimate),
         ("spray", Noun_Type.inanimate),
         ("surprise", Noun_Type.inanimate),
         ("till", Noun_Type.inanimate),
         ("transition", Noun_Type.inanimate),
         ("weekend", Noun_Type.inanimate),
         ("welcome", Noun_Type.inanimate),
         ("yard", Noun_Type.inanimate),
         ("alarm", Noun_Type.inanimate),
         ("bend", Noun_Type.inanimate),
         ("bicycle", Noun_Type.inanimate),
         ("bite", Noun_Type.inanimate),
         ("blind", Noun_Type.inanimate),
         ("bottle", Noun_Type.inanimate),
         ("cable", Noun_Type.inanimate),
         ("candle", Noun_Type.inanimate),
         ("clerk", Noun_Type.inanimate),
         ("cloud", Noun_Type.inanimate),
         ("concert", Noun_Type.inanimate),
         ("counter", Noun_Type.inanimate),
         ("flower", Noun_Type.inanimate),
         ("grandfather", Noun_Type.inanimate),
         ("harm", Noun_Type.inanimate),
         ("knee", Noun_Type.inanimate),
         ("lawyer", Noun_Type.inanimate),
         ("leather", Noun_Type.inanimate),
         ("load", Noun_Type.inanimate),
         ("mirror", Noun_Type.inanimate),
         ("neck", Noun_Type.inanimate),
         ("pension", Noun_Type.inanimate),
         ("plate", Noun_Type.inanimate),
         ("purple", Noun_Type.inanimate),
         ("ruin", Noun_Type.inanimate),
         ("ship", Noun_Type.inanimate),
         ("skirt", Noun_Type.inanimate),
         ("slice", Noun_Type.inanimate),
         ("snow", Noun_Type.inanimate),
         ("specialist", Noun_Type.inanimate),
         ("stroke", Noun_Type.inanimate),
         ("switch", Noun_Type.inanimate),
         ("trash", Noun_Type.inanimate),
         ("tune", Noun_Type.inanimate),
         ("zone", Noun_Type.inanimate),
         ("anger", Noun_Type.inanimate),
         ("award", Noun_Type.inanimate),
         ("bid", Noun_Type.inanimate),
         ("bitter", Noun_Type.inanimate),
         ("boot", Noun_Type.inanimate),
         ("bug", Noun_Type.inanimate),
         ("camp", Noun_Type.inanimate),
         ("candy", Noun_Type.inanimate),
         ("carpet", Noun_Type.inanimate),
         ("cat", Noun_Type.inanimate),
         ("champion", Noun_Type.inanimate),
         ("channel", Noun_Type.inanimate),
         ("clock", Noun_Type.inanimate),
         ("comfort", Noun_Type.inanimate),
         ("cow", Noun_Type.inanimate),
         ("crack", Noun_Type.inanimate),
         ("engineer", Noun_Type.inanimate),
         ("entrance", Noun_Type.inanimate),
         ("fault", Noun_Type.inanimate),
         ("grass", Noun_Type.inanimate),
         ("guy", Noun_Type.inanimate),
         ("hell", Noun_Type.inanimate),
         ("highlight", Noun_Type.inanimate),
         ("incident", Noun_Type.inanimate),
         ("island", Noun_Type.inanimate),
         ("joke", Noun_Type.inanimate),
         ("jury", Noun_Type.inanimate),
         ("leg", Noun_Type.inanimate),
         ("lip", Noun_Type.inanimate),
         ("mate", Noun_Type.inanimate),
         ("motor", Noun_Type.inanimate),
         ("nerve", Noun_Type.inanimate),
         ("passage", Noun_Type.inanimate),
         ("pen", Noun_Type.inanimate),
         ("pride", Noun_Type.inanimate),
         ("priest", Noun_Type.inanimate),
         ("prize", Noun_Type.inanimate),
         ("promise", Noun_Type.inanimate),
         ("resident", Noun_Type.inanimate),
         ("resort", Noun_Type.inanimate),
         ("ring", Noun_Type.inanimate),
         ("roof", Noun_Type.inanimate),
         ("rope", Noun_Type.inanimate),
         ("sail", Noun_Type.inanimate),
         ("scheme", Noun_Type.inanimate),
         ("script", Noun_Type.inanimate),
         ("sock", Noun_Type.inanimate),
         ("station", Noun_Type.inanimate),
         ("toe", Noun_Type.inanimate),
         ("tower", Noun_Type.inanimate),
         ("truck", Noun_Type.inanimate),
         ("witness", Noun_Type.inanimate),
         ("a", Noun_Type.inanimate),
         ("you", Noun_Type.inanimate),
         ("it", Noun_Type.inanimate),
         ("can", Noun_Type.inanimate),
         ("will", Noun_Type.inanimate),
         ("if", Noun_Type.inanimate),
         ("one", Noun_Type.inanimate),
         ("many", Noun_Type.inanimate),
         ("most", Noun_Type.inanimate),
         ("other", Noun_Type.inanimate),
         ("use", Noun_Type.inanimate),
         ("make", Noun_Type.inanimate),
         ("good", Noun_Type.inanimate),
         ("look", Noun_Type.inanimate),
         ("help", Noun_Type.inanimate),
         ("go", Noun_Type.inanimate),
         ("great", Noun_Type.inanimate),
         ("being", Noun_Type.inanimate),
         ("few", Noun_Type.inanimate),
         ("might", Noun_Type.inanimate),
         ("still", Noun_Type.inanimate),
         ("public", Noun_Type.inanimate),
         ("read", Noun_Type.inanimate),
         ("keep", Noun_Type.inanimate),
         ("start", Noun_Type.inanimate),
         ("give", Noun_Type.inanimate),
         ("human", Noun_Type.inanimate),
         ("local", Noun_Type.inanimate),
         ("general", Noun_Type.inanimate),
         ("she", Noun_Type.inanimate),
         ("specific", Noun_Type.inanimate),
         ("long", Noun_Type.inanimate),
         ("play", Noun_Type.inanimate),
         ("feel", Noun_Type.inanimate),
         ("high", Noun_Type.inanimate),
         ("tonight", Noun_Type.inanimate),
         ("put", Noun_Type.inanimate),
         ("common", Noun_Type.inanimate),
         ("set", Noun_Type.inanimate),
         ("change", Noun_Type.inanimate),
         ("simple", Noun_Type.inanimate),
         ("past", Noun_Type.inanimate),
         ("big", Noun_Type.inanimate),
         ("possible", Noun_Type.inanimate),
         ("particular", Noun_Type.inanimate),
         ("today", Noun_Type.inanimate),
         ("major", Noun_Type.inanimate),
         ("personal", Noun_Type.inanimate),
         ("current", Noun_Type.inanimate),
         ("national", Noun_Type.inanimate),
         ("cut", Noun_Type.inanimate),
         ("natural", Noun_Type.inanimate),
         ("physical", Noun_Type.inanimate),
         ("show", Noun_Type.inanimate),
         ("try", Noun_Type.inanimate),
         ("check", Noun_Type.inanimate),
         ("second", Noun_Type.inanimate),
         ("call", Noun_Type.inanimate),
         ("move", Noun_Type.inanimate),
         ("pay", Noun_Type.inanimate),
         ("let", Noun_Type.inanimate),
         ("increase", Noun_Type.inanimate),
         ("single", Noun_Type.inanimate),
         ("individual", Noun_Type.inanimate),
         ("turn", Noun_Type.inanimate),
         ("ask", Noun_Type.inanimate),
         ("buy", Noun_Type.inanimate),
         ("guard", Noun_Type.inanimate),
         ("hold", Noun_Type.inanimate),
         ("main", Noun_Type.inanimate),
         ("offer", Noun_Type.inanimate),
         ("potential", Noun_Type.inanimate),
         ("professional", Noun_Type.inanimate),
         ("international", Noun_Type.inanimate),
         ("travel", Noun_Type.inanimate),
         ("cook", Noun_Type.inanimate),
         ("alternative", Noun_Type.inanimate),
         ("following", Noun_Type.inanimate),
         ("special", Noun_Type.inanimate),
         ("working", Noun_Type.inanimate),
         ("whole", Noun_Type.inanimate),
         ("dance", Noun_Type.inanimate),
         ("excuse", Noun_Type.inanimate),
         ("cold", Noun_Type.inanimate),
         ("commercial", Noun_Type.inanimate),
         ("low", Noun_Type.inanimate),
         ("purchase", Noun_Type.inanimate),
         ("deal", Noun_Type.inanimate),
         ("primary", Noun_Type.inanimate),
         ("worth", Noun_Type.inanimate),
         ("fall", Noun_Type.inanimate),
         ("necessary", Noun_Type.inanimate),
         ("positive", Noun_Type.inanimate),
         ("produce", Noun_Type.inanimate),
         ("search", Noun_Type.inanimate),
         ("present", Noun_Type.inanimate),
         ("spend", Noun_Type.inanimate),
         ("talk", Noun_Type.inanimate),
         ("creative", Noun_Type.inanimate),
         ("tell", Noun_Type.inanimate),
         ("cost", Noun_Type.inanimate),
         ("drive", Noun_Type.inanimate),
         ("green", Noun_Type.inanimate),
         ("support", Noun_Type.inanimate),
         ("glad", Noun_Type.inanimate),
         ("remove", Noun_Type.inanimate),
         ("return", Noun_Type.inanimate),
         ("run", Noun_Type.inanimate),
         ("complex", Noun_Type.inanimate),
         ("due", Noun_Type.inanimate),
         ("effective", Noun_Type.inanimate),
         ("middle", Noun_Type.inanimate),
         ("regular", Noun_Type.inanimate),
         ("reserve", Noun_Type.inanimate),
         ("independent", Noun_Type.inanimate),
         ("leave", Noun_Type.inanimate),
         ("original", Noun_Type.inanimate),
         ("reach", Noun_Type.inanimate),
         ("rest", Noun_Type.inanimate),
         ("serve", Noun_Type.inanimate),
         ("watch", Noun_Type.inanimate),
         ("beautiful", Noun_Type.inanimate),
         ("charge", Noun_Type.inanimate),
         ("active", Noun_Type.inanimate),
         ("break", Noun_Type.inanimate),
         ("negative", Noun_Type.inanimate),
         ("safe", Noun_Type.inanimate),
         ("stay", Noun_Type.inanimate),
         ("visit", Noun_Type.inanimate),
         ("visual", Noun_Type.inanimate),
         ("affect", Noun_Type.inanimate),
         ("cover", Noun_Type.inanimate),
         ("report", Noun_Type.inanimate),
         ("rise", Noun_Type.inanimate),
         ("walk", Noun_Type.inanimate),
         ("white", Noun_Type.inanimate),
         ("beyond", Noun_Type.inanimate),
         ("junior", Noun_Type.inanimate),
         ("pick", Noun_Type.inanimate),
         ("unique", Noun_Type.inanimate),
         ("anything", Noun_Type.inanimate),
         ("classic", Noun_Type.inanimate),
         ("final", Noun_Type.inanimate),
         ("lift", Noun_Type.inanimate),
         ("mix", Noun_Type.inanimate),
         ("private", Noun_Type.inanimate),
         ("stop", Noun_Type.inanimate),
         ("teach", Noun_Type.inanimate),
         ("western", Noun_Type.inanimate),
         ("concern", Noun_Type.inanimate),
         ("familiar", Noun_Type.inanimate),
         ("fly", Noun_Type.inanimate),
         ("official", Noun_Type.inanimate),
         ("broad", Noun_Type.inanimate),
         ("comfortable", Noun_Type.inanimate),
         ("gain", Noun_Type.inanimate),
         ("maybe", Noun_Type.inanimate),
         ("rich", Noun_Type.inanimate),
         ("save", Noun_Type.inanimate),
         ("stand", Noun_Type.inanimate),
         ("young", Noun_Type.inanimate),
         ("fail", Noun_Type.inanimate),
         ("heavy", Noun_Type.inanimate),
         ("hello", Noun_Type.inanimate),
         ("lead", Noun_Type.inanimate),
         ("listen", Noun_Type.inanimate),
         ("valuable", Noun_Type.inanimate),
         ("worry", Noun_Type.inanimate),
         ("handle", Noun_Type.inanimate),
         ("leading", Noun_Type.inanimate),
         ("meet", Noun_Type.inanimate),
         ("release", Noun_Type.inanimate),
         ("sell", Noun_Type.inanimate),
         ("finish", Noun_Type.inanimate),
         ("normal", Noun_Type.inanimate),
         ("press", Noun_Type.inanimate),
         ("ride", Noun_Type.inanimate),
         ("secret", Noun_Type.inanimate),
         ("spread", Noun_Type.inanimate),
         ("spring", Noun_Type.inanimate),
         ("tough", Noun_Type.inanimate),
         ("wait", Noun_Type.inanimate),
         ("brown", Noun_Type.inanimate),
         ("deep", Noun_Type.inanimate),
         ("display", Noun_Type.inanimate),
         ("flow", Noun_Type.inanimate),
         ("hit", Noun_Type.inanimate),
         ("objective", Noun_Type.inanimate),
         ("shoot", Noun_Type.inanimate),
         ("touch", Noun_Type.inanimate),
         ("cancel", Noun_Type.inanimate),
         ("chemical", Noun_Type.inanimate),
         ("cry", Noun_Type.inanimate),
         ("dump", Noun_Type.inanimate),
         ("extreme", Noun_Type.inanimate),
         ("push", Noun_Type.inanimate),
         ("conflict", Noun_Type.inanimate),
         ("eat", Noun_Type.inanimate),
         ("fill", Noun_Type.inanimate),
         ("formal", Noun_Type.inanimate),
         ("jump", Noun_Type.inanimate),
         ("kick", Noun_Type.inanimate),
         ("opposite", Noun_Type.inanimate),
         ("pass", Noun_Type.inanimate),
         ("pitch", Noun_Type.inanimate),
         ("remote", Noun_Type.inanimate),
         ("total", Noun_Type.inanimate),
         ("treat", Noun_Type.inanimate),
         ("vast", Noun_Type.inanimate),
         ("abuse", Noun_Type.inanimate),
         ("beat", Noun_Type.inanimate),
         ("burn", Noun_Type.inanimate),
         ("deposit", Noun_Type.inanimate),
         ("print", Noun_Type.inanimate),
         ("raise", Noun_Type.inanimate),
         ("sleep", Noun_Type.inanimate),
         ("somewhere", Noun_Type.inanimate),
         ("advance", Noun_Type.inanimate),
         ("anywhere", Noun_Type.inanimate),
         ("consist", Noun_Type.inanimate),
         ("dark", Noun_Type.inanimate),
         ("double", Noun_Type.inanimate),
         ("draw", Noun_Type.inanimate),
         ("equal", Noun_Type.inanimate),
         ("fix", Noun_Type.inanimate),
         ("hire", Noun_Type.inanimate),
         ("internal", Noun_Type.inanimate),
         ("join", Noun_Type.inanimate),
         ("kill", Noun_Type.inanimate),
         ("sensitive", Noun_Type.inanimate),
         ("tap", Noun_Type.inanimate),
         ("win", Noun_Type.inanimate),
         ("attack", Noun_Type.inanimate),
         ("claim", Noun_Type.inanimate),
         ("constant", Noun_Type.inanimate),
         ("drag", Noun_Type.inanimate),
         ("drink", Noun_Type.inanimate),
         ("guess", Noun_Type.inanimate),
         ("minor", Noun_Type.inanimate),
         ("pull", Noun_Type.inanimate),
         ("raw", Noun_Type.inanimate),
         ("soft", Noun_Type.inanimate),
         ("solid", Noun_Type.inanimate),
         ("wear", Noun_Type.inanimate),
         ("weird", Noun_Type.inanimate),
         ("wonder", Noun_Type.inanimate),
         ("annual", Noun_Type.inanimate),
         ("count", Noun_Type.inanimate),
         ("dead", Noun_Type.inanimate),
         ("doubt", Noun_Type.inanimate),
         ("feed", Noun_Type.inanimate),
         ("forever", Noun_Type.inanimate),
         ("impress", Noun_Type.inanimate),
         ("nobody", Noun_Type.inanimate),
         ("repeat", Noun_Type.inanimate),
         ("round", Noun_Type.inanimate),
         ("sing", Noun_Type.inanimate),
         ("slide", Noun_Type.inanimate),
         ("strip", Noun_Type.inanimate),
         ("whereas", Noun_Type.inanimate),
         ("wish", Noun_Type.inanimate),
         ("combine", Noun_Type.inanimate),
         ("command", Noun_Type.inanimate),
         ("dig", Noun_Type.inanimate),
         ("divide", Noun_Type.inanimate),
         ("equivalent", Noun_Type.inanimate),
         ("hang", Noun_Type.inanimate),
         ("hunt", Noun_Type.inanimate),
         ("initial", Noun_Type.inanimate),
         ("march", Noun_Type.inanimate),
         ("mention", Noun_Type.inanimate),
         ("smell", Noun_Type.inanimate),
         ("spiritual", Noun_Type.inanimate),
         ("survey", Noun_Type.inanimate),
         ("tie", Noun_Type.inanimate),
         ("adult", Noun_Type.inanimate),
         ("brief", Noun_Type.inanimate),
         ("crazy", Noun_Type.inanimate),
         ("escape", Noun_Type.inanimate),
         ("gather", Noun_Type.inanimate),
         ("hate", Noun_Type.inanimate),
         ("prior", Noun_Type.inanimate),
         ("repair", Noun_Type.inanimate),
         ("rough", Noun_Type.inanimate),
         ("sad", Noun_Type.inanimate),
         ("scratch", Noun_Type.inanimate),
         ("sick", Noun_Type.inanimate),
         ("strike", Noun_Type.inanimate),
         ("employ", Noun_Type.inanimate),
         ("external", Noun_Type.inanimate),
         ("hurt", Noun_Type.inanimate),
         ("illegal", Noun_Type.inanimate),
         ("laugh", Noun_Type.inanimate),
         ("lay", Noun_Type.inanimate),
         ("mobile", Noun_Type.inanimate),
         ("nasty", Noun_Type.inanimate),
         ("ordinary", Noun_Type.inanimate),
         ("respond", Noun_Type.inanimate),
         ("royal", Noun_Type.inanimate),
         ("senior", Noun_Type.inanimate),
         ("split", Noun_Type.inanimate),
         ("strain", Noun_Type.inanimate),
         ("struggle", Noun_Type.inanimate),
         ("swim", Noun_Type.inanimate),
         ("train", Noun_Type.inanimate),
         ("upper", Noun_Type.inanimate),
         ("wash", Noun_Type.inanimate),
         ("yellow", Noun_Type.inanimate),
         ("convert", Noun_Type.inanimate),
         ("crash", Noun_Type.inanimate),
         ("dependent", Noun_Type.inanimate),
         ("fold", Noun_Type.inanimate),
         ("funny", Noun_Type.inanimate),
         ("grab", Noun_Type.inanimate),
         ("hide", Noun_Type.inanimate),
         ("miss", Noun_Type.inanimate),
         ("permit", Noun_Type.inanimate),
         ("quote", Noun_Type.inanimate),
         ("recover", Noun_Type.inanimate),
         ("resolve", Noun_Type.inanimate),
         ("roll", Noun_Type.inanimate),
         ("sink", Noun_Type.inanimate),
         ("slip", Noun_Type.inanimate),
         ("spare", Noun_Type.inanimate),
         ("suspect", Noun_Type.inanimate),
         ("sweet", Noun_Type.inanimate),
         ("swing", Noun_Type.inanimate),
         ("twist", Noun_Type.inanimate),
         ("upstairs", Noun_Type.inanimate),
         ("usual", Noun_Type.inanimate),
         ("abroad", Noun_Type.inanimate),
         ("brave", Noun_Type.inanimate),
         ("calm", Noun_Type.inanimate),
         ("concentrate", Noun_Type.inanimate),
         ("estimate", Noun_Type.inanimate),
         ("grand", Noun_Type.inanimate),
         ("male", Noun_Type.inanimate),
         ("mine", Noun_Type.inanimate),
         ("prompt", Noun_Type.inanimate),
         ("quiet", Noun_Type.inanimate),
         ("refuse", Noun_Type.inanimate),
         ("regret", Noun_Type.inanimate),
         ("reveal", Noun_Type.inanimate),
         ("rush", Noun_Type.inanimate),
         ("shake", Noun_Type.inanimate),
         ("shift", Noun_Type.inanimate),
         ("shine", Noun_Type.inanimate),
         ("steal", Noun_Type.inanimate),
         ("suck", Noun_Type.inanimate),
         ("surround", Noun_Type.inanimate),
         ("anybody", Noun_Type.inanimate),
         ("bear", Noun_Type.inanimate),
         ("brilliant", Noun_Type.inanimate),
         ("dare", Noun_Type.inanimate),
         ("dear", Noun_Type.inanimate),
         ("delay", Noun_Type.inanimate),
         ("drunk", Noun_Type.inanimate),
         ("female", Noun_Type.inanimate),
         ("hurry", Noun_Type.inanimate),
         ("inevitable", Noun_Type.inanimate),
         ("invite", Noun_Type.inanimate),
         ("kiss", Noun_Type.inanimate),
         ("neat", Noun_Type.inanimate),
         ("pop", Noun_Type.inanimate),
         ("punch", Noun_Type.inanimate),
         ("quit", Noun_Type.inanimate),
         ("reply", Noun_Type.inanimate),
         ("representative", Noun_Type.inanimate),
         ("resist", Noun_Type.inanimate),
         ("rip", Noun_Type.inanimate),
         ("rub", Noun_Type.inanimate),
         ("silly", Noun_Type.inanimate),
         ("smile", Noun_Type.inanimate),
         ("spell", Noun_Type.inanimate),
         ("stretch", Noun_Type.inanimate),
         ("stupid", Noun_Type.inanimate),
         ("tear", Noun_Type.inanimate),
         ("temporary", Noun_Type.inanimate),
         ("tomorrow", Noun_Type.inanimate),
         ("wake", Noun_Type.inanimate),
         ("wrap", Noun_Type.inanimate),
         ("yesterday", Noun_Type.inanimate)]

articles = [("the", Article_Type.improper), ("their", Article_Type.improper), ("my", Article_Type.improper),
            ("a", Article_Type.improper), ("", Article_Type.human), ("sir", Article_Type.human)]

verbs = [("sat", Verb_Type.either, [Prepositions.on_, Prepositions.in_]),
         ("jumped", Verb_Type.animate, [Prepositions.on_, Prepositions.in_]),
         ("ran", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("began", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("broke", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("brought", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("bought", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("built", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("chose", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("came", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("cost", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("cut", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("did", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("drew", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("drove", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("ate", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("felt", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("found", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("got", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("gave", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("went", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("had", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("heard", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("held", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("kept", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("knew", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("left", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("led", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("let", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("lay", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("lost", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("made", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("meant", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("met", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("paid", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("put", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("ran", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("said", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("sold", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("sent", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("set", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("sat", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("spoke", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("spent", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("stood", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("took", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("taught", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("told", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("thought", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("understood", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("wore", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("won", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("wrote", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("accepted", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("achieved", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("added", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("admired", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("admitted", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("adopted", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("advised", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("agreed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("allowed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("announced", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("appreciated", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("approved", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("argued", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("arrived", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("asked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("assisted", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("attacked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("baked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("begged", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("behaved", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("boiled", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("borrowed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("brushed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("buried", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("called", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("challenged", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("changed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("chased", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("cheated", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("cheered", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("chewed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("clapped", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("cleaned", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("collected", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("compared", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("complained", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("confessed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("constructed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("controlled", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("copied", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("counted", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("created", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("cried", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("cycled", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("damaged", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("danced", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("delivered", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("destroyed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("divided", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("dragged", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("earned", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("employed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("encouraged", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("enjoyed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("established", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("estimated", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("exercised", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("expanded", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("explained", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("fried", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("gathered", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("greeted", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("guessed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("harassed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("hated", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("helped", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("hoped", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("identified", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("interrupted", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("introduced", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("irritated", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("joked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("jumped", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("kicked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("killed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("kissed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("laughed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("lied", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("liked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("listened", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("loved", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("married", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("measured", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("moved", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("murdered", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("needed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("obeyed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("offended", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("offered", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("opened", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("painted", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("parked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("phoned", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("picked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("played", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("prayed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("printed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("pulled", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("punched", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("punished", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("purchased", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("pushed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("questioned", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("raced", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("relaxed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("remembered", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("replied", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("retired", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("returned", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("rubbed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("scolded", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("selected", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("smoked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("snored", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("stared", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("started", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("studied", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("talked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("thanked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("travelled", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("troubled", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("typed", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("used", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("visited", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("waited", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("walked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("wanted", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("warned", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("winked", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("worried", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("yelled", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_]),
         ("", Verb_Type.inanimate, [Prepositions.on_, Prepositions.in_])]


def pick_article_from_noun(noun_type):
    if noun_type is not Noun_Type.human:
        return random.choice([x for x in articles if x[1] is Article_Type.improper])
    else:
        return random.choice([x for x in articles if x[1] is Article_Type.human])


def pick_verb_from_noun(noun_type):
    if noun_type is Noun_Type.inanimate:
        return random.choice([x for x in verbs if x[1] in [Verb_Type.inanimate, Verb_Type.either]])
    else:
        return random.choice([x for x in verbs if x[1] in [Verb_Type.animate, Verb_Type.either]])


def pick_preposition_from_verb(verb):
    chosen = random.choice(verb[2])
    if chosen is Prepositions.in_:
        return "in"
    elif chosen is Prepositions.on_:
        return "on"
    else:
        raise Exception("Oh No you forgot to set a string for a preposition value!! what a bummer.")


def sentence_1():
    noun = random.choice(nouns)
    article = pick_article_from_noun(noun[1])
    verb = pick_verb_from_noun(noun[1])
    preposition = pick_preposition_from_verb(verb)
    noun2 = random.choice(nouns)
    article2 = pick_article_from_noun(noun2[1])

    return "{} {} {} {} {} {}!".format(article[0], noun[0], verb[0], preposition, article2[0], noun2[0])


def sentence_2():
    noun = random.choice(nouns)
    article = pick_article_from_noun(noun[1])
    verb = pick_verb_from_noun(noun[1])
    preposition = pick_preposition_from_verb(verb)
    noun2 = random.choice(nouns)

    return "{} {} {} {} {}!".format(article[0], noun[0], verb[0], preposition, noun2[0])


print(sentence_1())
